# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*\n"
"{\n"
"color: #fff;\n"
"font-family: \'Trebuchet MS\';\n"
"font-size: 16px;\n"
"border: nine;\n"
"background: none;\n"
"}\n"
"#centralwidget\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.48, stop:0 rgba(0, 100,180, 200), stop:1 rgba(0, 100, 115, 123));\n"
"}\n"
"#frame_navbar\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"border-radius: 5px;\n"
"font-size: 14px;\n"
"}\n"
"\n"
"#frame_navbar QPushButton:hover\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"\n"
"/*DataBase Window*/\n"
"QTableWidget{\n"
"    background-color: rgba(0,0,0,100);\n"
"    alternate-background-color: rgba(75, 105, 117, 100);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgba(139, 193, 212, 100);\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    color: rgb(60, 124, 149);\n"
"    background-color: rgb(60, 124, 149);\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    color: rgb(60, 124, 149);\n"
"    background-color: rgb(29, 101, 129);\n"
"    margin: 3px 0px 3px 0px;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    color: rgb(60, 124, 149);\n"
"    background-color: rgb(29, 101, 129);\n"
"    margin: 3px 0px 3px 0px;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on{\n"
"    color: rgb(60, 124, 149);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on{\n"
"    color: rgb(60, 124, 149);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"QHeaderView{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 50));\n"
"    padding: 4px;\n"
"    font-size: 14pt;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(0, 0, 0);\n"
"    border-right: 1px solid #000000;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_navbar = QtWidgets.QFrame(self.centralwidget)
        self.frame_navbar.setEnabled(True)
        self.frame_navbar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_navbar.setObjectName("frame_navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_navbar)
        self.horizontalLayout.setContentsMargins(11, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_login_menu = QtWidgets.QFrame(self.frame_navbar)
        self.frame_login_menu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_login_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_menu.setObjectName("frame_login_menu")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.frame_login_menu)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.button_login_menu = QtWidgets.QPushButton(self.frame_login_menu)
        self.button_login_menu.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_login_menu.setIcon(icon)
        self.button_login_menu.setIconSize(QtCore.QSize(20, 20))
        self.button_login_menu.setObjectName("button_login_menu")
        self.horizontalLayout_47.addWidget(self.button_login_menu)
        self.label_login_menu = QtWidgets.QLabel(self.frame_login_menu)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_login_menu.setFont(font)
        self.label_login_menu.setObjectName("label_login_menu")
        self.horizontalLayout_47.addWidget(self.label_login_menu)
        self.horizontalLayout.addWidget(self.frame_login_menu)
        self.frame_login_dash = QtWidgets.QFrame(self.frame_navbar)
        self.frame_login_dash.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_login_dash.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.frame_login_dash.setFont(font)
        self.frame_login_dash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_dash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_dash.setObjectName("frame_login_dash")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.frame_login_dash)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_login_dash = QtWidgets.QLabel(self.frame_login_dash)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_login_dash.setFont(font)
        self.label_login_dash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_dash.setObjectName("label_login_dash")
        self.horizontalLayout_48.addWidget(self.label_login_dash)
        self.horizontalLayout.addWidget(self.frame_login_dash)
        self.frame_login_ctrl = QtWidgets.QFrame(self.frame_navbar)
        self.frame_login_ctrl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_login_ctrl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_ctrl.setObjectName("frame_login_ctrl")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.frame_login_ctrl)
        self.horizontalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_49.setSpacing(2)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.button_login_min = QtWidgets.QPushButton(self.frame_login_ctrl)
        self.button_login_min.setMinimumSize(QtCore.QSize(30, 30))
        self.button_login_min.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus-sign-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_login_min.setIcon(icon1)
        self.button_login_min.setObjectName("button_login_min")
        self.horizontalLayout_49.addWidget(self.button_login_min)
        self.button_login_size = QtWidgets.QPushButton(self.frame_login_ctrl)
        self.button_login_size.setMinimumSize(QtCore.QSize(30, 30))
        self.button_login_size.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_size.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/aspect-ratio-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_login_size.setIcon(icon2)
        self.button_login_size.setObjectName("button_login_size")
        self.horizontalLayout_49.addWidget(self.button_login_size)
        self.button_login_exit = QtWidgets.QPushButton(self.frame_login_ctrl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_login_exit.sizePolicy().hasHeightForWidth())
        self.button_login_exit.setSizePolicy(sizePolicy)
        self.button_login_exit.setMinimumSize(QtCore.QSize(30, 30))
        self.button_login_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close-window-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_login_exit.setIcon(icon3)
        self.button_login_exit.setObjectName("button_login_exit")
        self.horizontalLayout_49.addWidget(self.button_login_exit)
        self.horizontalLayout.addWidget(self.frame_login_ctrl)
        self.verticalLayout.addWidget(self.frame_navbar)
        self.frame_stacked = QtWidgets.QFrame(self.centralwidget)
        self.frame_stacked.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_stacked.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_stacked.setObjectName("frame_stacked")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_stacked)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_stacked)
        self.stackedWidget.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setStyleSheet("#frame_home_main\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-bottom-right-radius: 20px;\n"
"    border-top-right-radius: 20px;\n"
"}\n"
"\n"
"#label_home_main\n"
"{\n"
"    font-size: 25px;\n"
"}\n"
"\n"
"#home_page QPushButton\n"
"{\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"\n"
"#home_page QPushButton:hover\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}")
        self.home_page.setObjectName("home_page")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.home_page)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_home_main = QtWidgets.QFrame(self.home_page)
        self.frame_home_main.setMaximumSize(QtCore.QSize(400, 500))
        self.frame_home_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_main.setObjectName("frame_home_main")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_home_main)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_home_label = QtWidgets.QFrame(self.frame_home_main)
        self.frame_home_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_label.setObjectName("frame_home_label")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_home_label)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_home_main = QtWidgets.QLabel(self.frame_home_label)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_home_main.setFont(font)
        self.label_home_main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_home_main.setObjectName("label_home_main")
        self.horizontalLayout_30.addWidget(self.label_home_main)
        self.verticalLayout_22.addWidget(self.frame_home_label)
        self.frame_home_login = QtWidgets.QFrame(self.frame_home_main)
        self.frame_home_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_login.setObjectName("frame_home_login")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_home_login)
        self.horizontalLayout_23.setContentsMargins(-1, 60, -1, 2)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.button_home_login = QtWidgets.QPushButton(self.frame_home_login)
        self.button_home_login.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_home_login.setObjectName("button_home_login")
        self.horizontalLayout_23.addWidget(self.button_home_login)
        self.verticalLayout_22.addWidget(self.frame_home_login)
        self.frame_home_register = QtWidgets.QFrame(self.frame_home_main)
        self.frame_home_register.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_register.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_register.setObjectName("frame_home_register")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_home_register)
        self.horizontalLayout_24.setContentsMargins(-1, 2, -1, 2)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.button_home_register = QtWidgets.QPushButton(self.frame_home_register)
        self.button_home_register.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_home_register.setObjectName("button_home_register")
        self.horizontalLayout_24.addWidget(self.button_home_register)
        self.verticalLayout_22.addWidget(self.frame_home_register)
        self.frame_home_database = QtWidgets.QFrame(self.frame_home_main)
        self.frame_home_database.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_home_database.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_home_database.setObjectName("frame_home_database")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_home_database)
        self.horizontalLayout_25.setContentsMargins(-1, 2, -1, 60)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.button_home_database = QtWidgets.QPushButton(self.frame_home_database)
        self.button_home_database.setMaximumSize(QtCore.QSize(300, 16777215))
        self.button_home_database.setObjectName("button_home_database")
        self.horizontalLayout_25.addWidget(self.button_home_database)
        self.verticalLayout_22.addWidget(self.frame_home_database)
        self.horizontalLayout_22.addWidget(self.frame_home_main)
        self.stackedWidget.addWidget(self.home_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.login_page.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.login_page.setStyleSheet("#frame_login_main\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"\n"
"#frame_login_blogin QPushButton{\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"\n"
"#frame_login_bregister QPushButton{\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"\n"
"\n"
"#frame_login_blogin QPushButton:hover\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"\n"
"#frame_login_bregister QPushButton:hover\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"\n"
"#label_login_main\n"
"{\n"
"    font-size: 25px; \n"
"}")
        self.login_page.setObjectName("login_page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.login_page)
        self.horizontalLayout_12.setContentsMargins(11, -1, 11, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_login_main = QtWidgets.QFrame(self.login_page)
        self.frame_login_main.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_login_main.setMaximumSize(QtCore.QSize(400, 500))
        self.frame_login_main.setStyleSheet("")
        self.frame_login_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_main.setObjectName("frame_login_main")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_login_main)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_login_label = QtWidgets.QFrame(self.frame_login_main)
        self.frame_login_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_label.setObjectName("frame_login_label")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_login_label)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_login_main = QtWidgets.QLabel(self.frame_login_label)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_login_main.setFont(font)
        self.label_login_main.setObjectName("label_login_main")
        self.verticalLayout_5.addWidget(self.label_login_main, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.frame_login_label)
        self.frame_login_edit = QtWidgets.QFrame(self.frame_login_main)
        self.frame_login_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_edit.setObjectName("frame_login_edit")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_login_edit)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_login_id_2 = QtWidgets.QLineEdit(self.frame_login_edit)
        self.edit_login_id_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.edit_login_id_2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(255, 255, 255, 155);\n"
"\n"
"color:rgba(50,50,50,250);\n"
"padding-bottom:7px;")
        self.edit_login_id_2.setObjectName("edit_login_id_2")
        self.horizontalLayout_2.addWidget(self.edit_login_id_2)
        self.verticalLayout_4.addWidget(self.frame_login_edit, 0, QtCore.Qt.AlignBottom)
        self.frame_login_blogin = QtWidgets.QFrame(self.frame_login_main)
        self.frame_login_blogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_blogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_blogin.setObjectName("frame_login_blogin")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_login_blogin)
        self.horizontalLayout_4.setContentsMargins(-1, 60, -1, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_login_login = QtWidgets.QPushButton(self.frame_login_blogin)
        self.button_login_login.setMaximumSize(QtCore.QSize(200, 16777215))
        self.button_login_login.setObjectName("button_login_login")
        self.horizontalLayout_4.addWidget(self.button_login_login)
        self.verticalLayout_4.addWidget(self.frame_login_blogin, 0, QtCore.Qt.AlignBottom)
        self.frame_login_bregister = QtWidgets.QFrame(self.frame_login_main)
        self.frame_login_bregister.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_bregister.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_bregister.setObjectName("frame_login_bregister")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_login_bregister)
        self.horizontalLayout_3.setContentsMargins(-1, 5, -1, 60)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_login_sign = QtWidgets.QPushButton(self.frame_login_bregister)
        self.button_login_sign.setMaximumSize(QtCore.QSize(200, 16777215))
        self.button_login_sign.setObjectName("button_login_sign")
        self.horizontalLayout_3.addWidget(self.button_login_sign)
        self.verticalLayout_4.addWidget(self.frame_login_bregister, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_12.addWidget(self.frame_login_main)
        self.stackedWidget.addWidget(self.login_page)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.register_page.setStyleSheet("#label_create_main\n"
"{\n"
"    font-size: 25px;\n"
"}\n"
"\n"
"#frame_register_main\n"
"{\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"}\n"
"\n"
"#edit_signup_id\n"
"{\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(255, 255, 255, 155);\n"
"    color:rgba(50,50,50,250);\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"#edit_signup_nama\n"
"{\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(255, 255, 255, 155);\n"
"    color:rgba(50,50,50,250);\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"#edit_signup_umur\n"
"{\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(255, 255, 255, 155);\n"
"    color:rgba(50,50,50,250);\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"#frame_signup_button QPushButton{\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"\n"
"\n"
"#frame_signup_button QPushButton:hover\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"\n"
"#frame_signup_combobox QComboBox{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#frame_signup_combobox QComboBox QAbstractItemView{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"}")
        self.register_page.setObjectName("register_page")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.register_page)
        self.horizontalLayout_11.setContentsMargins(11, -1, 11, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_register_main = QtWidgets.QFrame(self.register_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_register_main.sizePolicy().hasHeightForWidth())
        self.frame_register_main.setSizePolicy(sizePolicy)
        self.frame_register_main.setMaximumSize(QtCore.QSize(400, 500))
        self.frame_register_main.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_register_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_register_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_register_main.setObjectName("frame_register_main")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_register_main)
        self.verticalLayout_7.setContentsMargins(25, -1, 25, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_create = QtWidgets.QFrame(self.frame_register_main)
        self.frame_create.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_create.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_create.setObjectName("frame_create")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_create)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_create_main = QtWidgets.QLabel(self.frame_create)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_create_main.setFont(font)
        self.label_create_main.setObjectName("label_create_main")
        self.horizontalLayout_5.addWidget(self.label_create_main)
        self.verticalLayout_7.addWidget(self.frame_create, 0, QtCore.Qt.AlignHCenter)
        self.frame_signup_id = QtWidgets.QFrame(self.frame_register_main)
        self.frame_signup_id.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_id.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_id.setObjectName("frame_signup_id")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_signup_id)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.edit_signup_id = QtWidgets.QLineEdit(self.frame_signup_id)
        self.edit_signup_id.setObjectName("edit_signup_id")
        self.horizontalLayout_10.addWidget(self.edit_signup_id)
        self.verticalLayout_7.addWidget(self.frame_signup_id)
        self.frame_signup_nama = QtWidgets.QFrame(self.frame_register_main)
        self.frame_signup_nama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_nama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_nama.setObjectName("frame_signup_nama")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_signup_nama)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.edit_signup_nama = QtWidgets.QLineEdit(self.frame_signup_nama)
        self.edit_signup_nama.setObjectName("edit_signup_nama")
        self.horizontalLayout_9.addWidget(self.edit_signup_nama)
        self.verticalLayout_7.addWidget(self.frame_signup_nama)
        self.frame_signup_umur = QtWidgets.QFrame(self.frame_register_main)
        self.frame_signup_umur.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_umur.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_umur.setObjectName("frame_signup_umur")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_signup_umur)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.edit_signup_umur = QtWidgets.QLineEdit(self.frame_signup_umur)
        self.edit_signup_umur.setObjectName("edit_signup_umur")
        self.horizontalLayout_8.addWidget(self.edit_signup_umur)
        self.verticalLayout_7.addWidget(self.frame_signup_umur)
        self.frame_signup_label = QtWidgets.QFrame(self.frame_register_main)
        self.frame_signup_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_label.setObjectName("frame_signup_label")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_signup_label)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_gender = QtWidgets.QLabel(self.frame_signup_label)
        self.label_gender.setObjectName("label_gender")
        self.horizontalLayout_6.addWidget(self.label_gender)
        self.verticalLayout_7.addWidget(self.frame_signup_label)
        self.frame_signup_combobox = QtWidgets.QFrame(self.frame_register_main)
        self.frame_signup_combobox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_combobox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_combobox.setObjectName("frame_signup_combobox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_signup_combobox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.combobox_signup_gender = QtWidgets.QComboBox(self.frame_signup_combobox)
        self.combobox_signup_gender.setObjectName("combobox_signup_gender")
        self.combobox_signup_gender.addItem("")
        self.combobox_signup_gender.addItem("")
        self.horizontalLayout_7.addWidget(self.combobox_signup_gender)
        self.verticalLayout_7.addWidget(self.frame_signup_combobox)
        self.frame_signup_button = QtWidgets.QFrame(self.frame_register_main)
        self.frame_signup_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_button.setObjectName("frame_signup_button")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_signup_button)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.button_signup_sign = QtWidgets.QPushButton(self.frame_signup_button)
        self.button_signup_sign.setMaximumSize(QtCore.QSize(200, 16777215))
        self.button_signup_sign.setObjectName("button_signup_sign")
        self.horizontalLayout_13.addWidget(self.button_signup_sign)
        self.verticalLayout_7.addWidget(self.frame_signup_button)
        self.horizontalLayout_11.addWidget(self.frame_register_main)
        self.stackedWidget.addWidget(self.register_page)
        self.database_page = QtWidgets.QWidget()
        self.database_page.setStyleSheet("#frame_database_menu\n"
"{\n"
"    border-radius: 10px;\n"
"    /*background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));*/\n"
"}\n"
"\n"
"#edit_database_id\n"
"{\n"
"    background-color: white;\n"
"}\n"
"\n"
"#edit_database_nama\n"
"{\n"
"    background-color: white;\n"
"}\n"
"\n"
"#frame_button_back QPushButton{\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"#frame_button_back QPushButton:hover\n"
"{\n"
"border-radius: 10px;\n"
"background-color: rgb(120, 157, 186);\n"
"}\n"
"\n"
"#frame_button_delete QPushButton{\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"#frame_button_delete QPushButton:hover\n"
"{\n"
"border-radius: 10px;\n"
"background-color: rgb(120, 157, 186);\n"
"}\n"
"")
        self.database_page.setObjectName("database_page")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.database_page)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_table = QtWidgets.QFrame(self.database_page)
        self.frame_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_table.setObjectName("frame_table")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_table)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_database_data = QtWidgets.QTableWidget(self.frame_table)
        self.table_database_data.setFrameShape(QtWidgets.QFrame.VLine)
        self.table_database_data.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table_database_data.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_database_data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_database_data.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_database_data.setAutoScroll(True)
        self.table_database_data.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_database_data.setAlternatingRowColors(True)
        self.table_database_data.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_database_data.setTextElideMode(QtCore.Qt.ElideLeft)
        self.table_database_data.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_database_data.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_database_data.setRowCount(4)
        self.table_database_data.setObjectName("table_database_data")
        self.table_database_data.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_database_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_database_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_database_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_database_data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_database_data.setHorizontalHeaderItem(4, item)
        self.table_database_data.horizontalHeader().setCascadingSectionResizes(False)
        self.table_database_data.horizontalHeader().setMinimumSectionSize(39)
        self.table_database_data.horizontalHeader().setSortIndicatorShown(True)
        self.table_database_data.horizontalHeader().setStretchLastSection(True)
        self.table_database_data.verticalHeader().setVisible(False)
        self.table_database_data.verticalHeader().setCascadingSectionResizes(False)
        self.table_database_data.verticalHeader().setSortIndicatorShown(False)
        self.table_database_data.setColumnWidth(3, 200)
        self.verticalLayout_3.addWidget(self.table_database_data)
        self.frame_database_menu = QtWidgets.QFrame(self.frame_table)
        self.frame_database_menu.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_database_menu.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_database_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_menu.setObjectName("frame_database_menu")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_database_menu)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_database_left = QtWidgets.QFrame(self.frame_database_menu)
        self.frame_database_left.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_database_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_left.setObjectName("frame_database_left")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_database_left)
        self.verticalLayout_6.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_database_id = QtWidgets.QFrame(self.frame_database_left)
        self.frame_database_id.setMinimumSize(QtCore.QSize(0, 10))
        self.frame_database_id.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_id.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_id.setObjectName("frame_database_id")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_database_id)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(7)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_database_id = QtWidgets.QLabel(self.frame_database_id)
        self.label_database_id.setObjectName("label_database_id")
        self.horizontalLayout_16.addWidget(self.label_database_id)
        self.edit_database_id = QtWidgets.QLineEdit(self.frame_database_id)
        self.edit_database_id.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_database_id.setObjectName("edit_database_id")
        self.horizontalLayout_16.addWidget(self.edit_database_id)
        self.verticalLayout_6.addWidget(self.frame_database_id)
        self.frame_button_back = QtWidgets.QFrame(self.frame_database_left)
        self.frame_button_back.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_back.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_back.setObjectName("frame_button_back")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_button_back)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.button_database_back = QtWidgets.QPushButton(self.frame_button_back)
        self.button_database_back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_database_back.setObjectName("button_database_back")
        self.horizontalLayout_17.addWidget(self.button_database_back)
        self.verticalLayout_6.addWidget(self.frame_button_back)
        self.horizontalLayout_15.addWidget(self.frame_database_left)
        self.frame_database_right = QtWidgets.QFrame(self.frame_database_menu)
        self.frame_database_right.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_database_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_right.setObjectName("frame_database_right")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_database_right)
        self.verticalLayout_8.setContentsMargins(0, 11, 0, 11)
        self.verticalLayout_8.setSpacing(7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_database_nama = QtWidgets.QFrame(self.frame_database_right)
        self.frame_database_nama.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_nama.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_nama.setObjectName("frame_database_nama")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_database_nama)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(7)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_database_nama = QtWidgets.QLabel(self.frame_database_nama)
        self.label_database_nama.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_database_nama.setObjectName("label_database_nama")
        self.horizontalLayout_18.addWidget(self.label_database_nama)
        self.edit_database_nama = QtWidgets.QLineEdit(self.frame_database_nama)
        self.edit_database_nama.setMaximumSize(QtCore.QSize(200, 16777215))
        self.edit_database_nama.setObjectName("edit_database_nama")
        self.horizontalLayout_18.addWidget(self.edit_database_nama)
        self.verticalLayout_8.addWidget(self.frame_database_nama)
        self.frame_button_delete = QtWidgets.QFrame(self.frame_database_right)
        self.frame_button_delete.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button_delete.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button_delete.setObjectName("frame_button_delete")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_button_delete)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.button_database_delete = QtWidgets.QPushButton(self.frame_button_delete)
        self.button_database_delete.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_database_delete.setObjectName("button_database_delete")
        self.horizontalLayout_19.addWidget(self.button_database_delete)
        self.verticalLayout_8.addWidget(self.frame_button_delete)
        self.horizontalLayout_15.addWidget(self.frame_database_right)
        self.verticalLayout_3.addWidget(self.frame_database_menu, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_14.addWidget(self.frame_table)
        self.stackedWidget.addWidget(self.database_page)
        self.graph_page = QtWidgets.QWidget()
        self.graph_page.setStyleSheet("#frame_graph_gbframe QComboBox\n"
"{\n"
"text-align: center;\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"#frame_graph_gbframe QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(61, 80, 95, 100);\n"
"}\n"
"#winmenu_graph\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.48, stop:0 rgba(0, 100,180, 200), stop:1 rgba(0, 100, 115, 123));\n"
"}\n"
"#frame_graph_head, #frame_graph_tframe\n"
"{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"border-radius: 5px;\n"
"font-size: 14px;\n"
"}\n"
"#frame_graph_left, #widget_main_graph, #widget_average_graph, #widget_sensors_graph, #frame_graph_inleft, #frame_graph_inright\n"
"{\n"
"background-color: rgba(61, 80, 95, 100);\n"
"}\n"
"#label_graph_tlabel\n"
"{\n"
"    font-family: \'Segoe UI\';\n"
"    font-size: 24px;\n"
"}\n"
"#frame_graph_inleft QLabel\n"
"{\n"
"font-size: 14px;\n"
"}\n"
"#frame_graph_inright QLabel\n"
"{\n"
"font-size: 14px;\n"
"}\n"
"#frame_graph_gbframe QPushButton\n"
"{\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"#frame_graph_gbframe QPushButton:hover\n"
"{\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgb(120, 157, 186);\n"
"}\n"
"#frame_graph_sframe QPushButton\n"
"{\n"
"    padding: 12px;\n"
"    border-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"}\n"
"#frame_graph_sframe QPushButton:hover\n"
"{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"#frame_graph_head QPushButton\n"
"{\n"
"    background-color: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"#frame_graph_head QPushButton:hover\n"
"{\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"#frame_graph_menu QPushButton:hover\n"
"{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"#frame_graph_util QPushButton\n"
"{\n"
"font-size: 13px;\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"#frame_graph_util QPushButton:hover\n"
"{\n"
"    border-radius: 5px;\n"
"    background-color: rgba(61, 80, 95, 100)\n"
"}")
        self.graph_page.setObjectName("graph_page")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.graph_page)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame = QtWidgets.QFrame(self.graph_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_graph_left = QtWidgets.QWidget(self.frame)
        self.frame_graph_left.setObjectName("frame_graph_left")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_graph_left)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_graph_tframe = QtWidgets.QFrame(self.frame_graph_left)
        self.frame_graph_tframe.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_graph_tframe.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_graph_tframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_tframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_tframe.setObjectName("frame_graph_tframe")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_graph_tframe)
        self.horizontalLayout_21.setContentsMargins(0, 0, 15, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_graph_ticon = QtWidgets.QLabel(self.frame_graph_tframe)
        self.label_graph_ticon.setMinimumSize(QtCore.QSize(40, 40))
        self.label_graph_ticon.setMaximumSize(QtCore.QSize(40, 40))
        self.label_graph_ticon.setText("")
        self.label_graph_ticon.setPixmap(QtGui.QPixmap(":/icons/icons/bar-chart-icon.svg"))
        self.label_graph_ticon.setScaledContents(True)
        self.label_graph_ticon.setObjectName("label_graph_ticon")
        self.horizontalLayout_21.addWidget(self.label_graph_ticon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_graph_tlabel = QtWidgets.QLabel(self.frame_graph_tframe)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_graph_tlabel.setFont(font)
        self.label_graph_tlabel.setObjectName("label_graph_tlabel")
        self.horizontalLayout_21.addWidget(self.label_graph_tlabel, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_9.addWidget(self.frame_graph_tframe)
        self.frame_graph_gbframe = QtWidgets.QFrame(self.frame_graph_left)
        self.frame_graph_gbframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_gbframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_gbframe.setObjectName("frame_graph_gbframe")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_graph_gbframe)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.button_graph_main = QtWidgets.QPushButton(self.frame_graph_gbframe)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.button_graph_main.setFont(font)
        icon = QtGui.QIcon.fromTheme("SP_ArrowBack")
        self.button_graph_main.setIcon(icon)
        self.button_graph_main.setObjectName("button_graph_main")
        self.verticalLayout_10.addWidget(self.button_graph_main)
        self.button_graph_average = QtWidgets.QPushButton(self.frame_graph_gbframe)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.button_graph_average.setFont(font)
        self.button_graph_average.setObjectName("button_graph_average")
        self.verticalLayout_10.addWidget(self.button_graph_average)
        self.combo_graph_sensors = QtWidgets.QComboBox(self.frame_graph_gbframe)
        self.combo_graph_sensors.setStyleSheet("QComboBox QAbstractItemView::item:hover {\n"
"    background-color: black;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    color: black;\n"
"}\n"
"QComboBox {\n"
"    text-align: center;\n"
"}\n"
"")
        self.combo_graph_sensors.setEditable(False)
        self.combo_graph_sensors.setObjectName("combo_graph_sensors")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.verticalLayout_10.addWidget(self.combo_graph_sensors)
        self.verticalLayout_9.addWidget(self.frame_graph_gbframe, 0, QtCore.Qt.AlignTop)
        self.frame_graph_sframe = QtWidgets.QFrame(self.frame_graph_left)
        self.frame_graph_sframe.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_graph_sframe.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_graph_sframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_sframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_sframe.setObjectName("frame_graph_sframe")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_graph_sframe)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.button_graph_load = QtWidgets.QPushButton(self.frame_graph_sframe)
        self.button_graph_load.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/engine-gears-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_graph_load.setIcon(icon4)
        self.button_graph_load.setObjectName("button_graph_load")
        self.verticalLayout_13.addWidget(self.button_graph_load)
        self.verticalLayout_9.addWidget(self.frame_graph_sframe)
        self.frame_graph_crlframe = QtWidgets.QFrame(self.frame_graph_left)
        self.frame_graph_crlframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_crlframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_crlframe.setObjectName("frame_graph_crlframe")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_graph_crlframe)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_graph_crllabel2 = QtWidgets.QLabel(self.frame_graph_crlframe)
        self.frame_graph_crllabel2.setObjectName("frame_graph_crllabel2")
        self.verticalLayout_11.addWidget(self.frame_graph_crllabel2)
        self.frame_graph_crllabel1 = QtWidgets.QLabel(self.frame_graph_crlframe)
        self.frame_graph_crllabel1.setObjectName("frame_graph_crllabel1")
        self.verticalLayout_11.addWidget(self.frame_graph_crllabel1)
        self.frame_graph_crllabel3 = QtWidgets.QLabel(self.frame_graph_crlframe)
        self.frame_graph_crllabel3.setObjectName("frame_graph_crllabel3")
        self.verticalLayout_11.addWidget(self.frame_graph_crllabel3)
        self.verticalLayout_9.addWidget(self.frame_graph_crlframe, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_29.addWidget(self.frame_graph_left)
        self.frame_graph_right = QtWidgets.QFrame(self.frame)
        self.frame_graph_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_right.setObjectName("frame_graph_right")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_graph_right)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_graph_swframe = QtWidgets.QFrame(self.frame_graph_right)
        self.frame_graph_swframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_swframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_swframe.setObjectName("frame_graph_swframe")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_graph_swframe)
        self.horizontalLayout_26.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.swidget_graph_swgraph = QtWidgets.QStackedWidget(self.frame_graph_swframe)
        self.swidget_graph_swgraph.setObjectName("swidget_graph_swgraph")
        self.widget_main_graph = QtWidgets.QWidget()
        self.widget_main_graph.setObjectName("widget_main_graph")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_main_graph)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_graph_mlabel = QtWidgets.QFrame(self.widget_main_graph)
        self.frame_graph_mlabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_mlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_mlabel.setObjectName("frame_graph_mlabel")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_graph_mlabel)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_graph_main = QtWidgets.QLabel(self.frame_graph_mlabel)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_graph_main.setFont(font)
        self.label_graph_main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_graph_main.setObjectName("label_graph_main")
        self.verticalLayout_15.addWidget(self.label_graph_main, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_14.addWidget(self.frame_graph_mlabel, 0, QtCore.Qt.AlignTop)
        self.frame_graph_mgraph = QtWidgets.QFrame(self.widget_main_graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graph_mgraph.sizePolicy().hasHeightForWidth())
        self.frame_graph_mgraph.setSizePolicy(sizePolicy)
        self.frame_graph_mgraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_mgraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_mgraph.setObjectName("frame_graph_mgraph")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_graph_mgraph)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_14.addWidget(self.frame_graph_mgraph)
        self.swidget_graph_swgraph.addWidget(self.widget_main_graph)
        self.widget_average_graph = QtWidgets.QWidget()
        self.widget_average_graph.setObjectName("widget_average_graph")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_average_graph)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_graph_avglabel = QtWidgets.QFrame(self.widget_average_graph)
        self.frame_graph_avglabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_avglabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_avglabel.setObjectName("frame_graph_avglabel")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_graph_avglabel)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_graph_average = QtWidgets.QLabel(self.frame_graph_avglabel)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_graph_average.setFont(font)
        self.label_graph_average.setAlignment(QtCore.Qt.AlignCenter)
        self.label_graph_average.setObjectName("label_graph_average")
        self.verticalLayout_17.addWidget(self.label_graph_average, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_16.addWidget(self.frame_graph_avglabel)
        self.frame_graph_avggraph = QtWidgets.QFrame(self.widget_average_graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graph_avggraph.sizePolicy().hasHeightForWidth())
        self.frame_graph_avggraph.setSizePolicy(sizePolicy)
        self.frame_graph_avggraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_avggraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_avggraph.setObjectName("frame_graph_avggraph")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_graph_avggraph)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_16.addWidget(self.frame_graph_avggraph)
        self.swidget_graph_swgraph.addWidget(self.widget_average_graph)
        self.widget_sensors_graph = QtWidgets.QWidget()
        self.widget_sensors_graph.setObjectName("widget_sensors_graph")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_sensors_graph)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_graph_slabel = QtWidgets.QFrame(self.widget_sensors_graph)
        self.frame_graph_slabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_slabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_slabel.setObjectName("frame_graph_slabel")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_graph_slabel)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_graph_sensor = QtWidgets.QLabel(self.frame_graph_slabel)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        self.label_graph_sensor.setFont(font)
        self.label_graph_sensor.setAlignment(QtCore.Qt.AlignCenter)
        self.label_graph_sensor.setObjectName("label_graph_sensor")
        self.verticalLayout_19.addWidget(self.label_graph_sensor, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_18.addWidget(self.frame_graph_slabel)
        self.frame_graph_sgraph = QtWidgets.QFrame(self.widget_sensors_graph)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_graph_sgraph.sizePolicy().hasHeightForWidth())
        self.frame_graph_sgraph.setSizePolicy(sizePolicy)
        self.frame_graph_sgraph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_sgraph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_sgraph.setObjectName("frame_graph_sgraph")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_graph_sgraph)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_18.addWidget(self.frame_graph_sgraph)
        self.swidget_graph_swgraph.addWidget(self.widget_sensors_graph)
        self.horizontalLayout_26.addWidget(self.swidget_graph_swgraph)
        self.verticalLayout_12.addWidget(self.frame_graph_swframe)
        self.frame_graph_util = QtWidgets.QFrame(self.frame_graph_right)
        self.frame_graph_util.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_util.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_util.setObjectName("frame_graph_util")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_graph_util)
        self.horizontalLayout_27.setContentsMargins(-1, 0, 11, 5)
        self.horizontalLayout_27.setSpacing(15)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.button_graph_start = QtWidgets.QPushButton(self.frame_graph_util)
        self.button_graph_start.setObjectName("button_graph_start")
        self.horizontalLayout_27.addWidget(self.button_graph_start)
        self.button_graph_stop = QtWidgets.QPushButton(self.frame_graph_util)
        self.button_graph_stop.setObjectName("button_graph_stop")
        self.horizontalLayout_27.addWidget(self.button_graph_stop)
        self.button_graph_save = QtWidgets.QPushButton(self.frame_graph_util)
        self.button_graph_save.setObjectName("button_graph_save")
        self.horizontalLayout_27.addWidget(self.button_graph_save)
        self.verticalLayout_12.addWidget(self.frame_graph_util)
        self.frame_graph_info = QtWidgets.QFrame(self.frame_graph_right)
        self.frame_graph_info.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_graph_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_info.setObjectName("frame_graph_info")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_graph_info)
        self.horizontalLayout_28.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_28.setSpacing(10)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.frame_graph_inleft = QtWidgets.QFrame(self.frame_graph_info)
        self.frame_graph_inleft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_inleft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_inleft.setObjectName("frame_graph_inleft")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_graph_inleft)
        self.verticalLayout_20.setContentsMargins(15, 10, 10, 10)
        self.verticalLayout_20.setSpacing(4)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_graph_id = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_id.setObjectName("label_graph_id")
        self.verticalLayout_20.addWidget(self.label_graph_id)
        self.label_graph_name = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_name.setObjectName("label_graph_name")
        self.verticalLayout_20.addWidget(self.label_graph_name)
        self.label_graph_gender = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_gender.setObjectName("label_graph_gender")
        self.verticalLayout_20.addWidget(self.label_graph_gender)
        self.label_graph_umur = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_umur.setObjectName("label_graph_umur")
        self.verticalLayout_20.addWidget(self.label_graph_umur)
        self.horizontalLayout_28.addWidget(self.frame_graph_inleft, 0, QtCore.Qt.AlignVCenter)
        self.frame_graph_inright = QtWidgets.QFrame(self.frame_graph_info)
        self.frame_graph_inright.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_inright.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_inright.setObjectName("frame_graph_inright")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_graph_inright)
        self.verticalLayout_21.setContentsMargins(15, 10, 10, 10)
        self.verticalLayout_21.setSpacing(4)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_graph_max = QtWidgets.QLabel(self.frame_graph_inright)
        self.label_graph_max.setObjectName("label_graph_max")
        self.verticalLayout_21.addWidget(self.label_graph_max)
        self.label_graph_min = QtWidgets.QLabel(self.frame_graph_inright)
        self.label_graph_min.setObjectName("label_graph_min")
        self.verticalLayout_21.addWidget(self.label_graph_min)
        self.label_graph_avg = QtWidgets.QLabel(self.frame_graph_inright)
        self.label_graph_avg.setObjectName("label_graph_avg")
        self.verticalLayout_21.addWidget(self.label_graph_avg)
        self.horizontalLayout_28.addWidget(self.frame_graph_inright)
        self.verticalLayout_12.addWidget(self.frame_graph_info, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_29.addWidget(self.frame_graph_right)
        self.horizontalLayout_20.addWidget(self.frame)
        self.stackedWidget.addWidget(self.graph_page)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_stacked)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.swidget_graph_swgraph.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_login_menu.setText(_translate("MainWindow", "MENU"))
        self.label_login_dash.setText(_translate("MainWindow", "DASHBOARD"))
        self.label_home_main.setText(_translate("MainWindow", "MAIN MENU"))
        self.button_home_login.setText(_translate("MainWindow", "Login"))
        self.button_home_register.setText(_translate("MainWindow", "Register"))
        self.button_home_database.setText(_translate("MainWindow", "Database"))
        self.label_login_main.setText(_translate("MainWindow", "LOG IN"))
        self.edit_login_id_2.setPlaceholderText(_translate("MainWindow", "ID Pasien"))
        self.button_login_login.setText(_translate("MainWindow", "Login"))
        self.button_login_sign.setText(_translate("MainWindow", "Register"))
        self.label_create_main.setText(_translate("MainWindow", "PENDAFTARAN"))
        self.edit_signup_id.setPlaceholderText(_translate("MainWindow", "ID"))
        self.edit_signup_nama.setPlaceholderText(_translate("MainWindow", "Nama"))
        self.edit_signup_umur.setPlaceholderText(_translate("MainWindow", "Umur"))
        self.label_gender.setText(_translate("MainWindow", "Jenis Kelamin:"))
        self.combobox_signup_gender.setItemText(0, _translate("MainWindow", "Laki-laki"))
        self.combobox_signup_gender.setItemText(1, _translate("MainWindow", "Perempuan"))
        self.button_signup_sign.setText(_translate("MainWindow", "Register"))
        self.table_database_data.setSortingEnabled(True)
        item = self.table_database_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_database_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.table_database_data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Usia"))
        item = self.table_database_data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Jenis Kelamin"))
        self.label_database_id.setText(_translate("MainWindow", "ID"))
        self.button_database_back.setText(_translate("MainWindow", "Back"))
        self.label_database_nama.setText(_translate("MainWindow", "Nama"))
        self.button_database_delete.setText(_translate("MainWindow", "Delete"))
        self.label_graph_tlabel.setText(_translate("MainWindow", "PLOT GRAPH"))
        self.button_graph_main.setText(_translate("MainWindow", "Main Graph"))
        self.button_graph_average.setText(_translate("MainWindow", "Average Graph"))
        self.combo_graph_sensors.setCurrentText(_translate("MainWindow", "Sensors Graph"))
        self.combo_graph_sensors.setItemText(0, _translate("MainWindow", "Sensors Graph"))
        self.combo_graph_sensors.setItemText(1, _translate("MainWindow", "Sensor 1"))
        self.combo_graph_sensors.setItemText(2, _translate("MainWindow", "Sensor 2"))
        self.combo_graph_sensors.setItemText(3, _translate("MainWindow", "Sensor 3"))
        self.combo_graph_sensors.setItemText(4, _translate("MainWindow", "Sensor 4"))
        self.combo_graph_sensors.setItemText(5, _translate("MainWindow", "Sensor 5"))
        self.combo_graph_sensors.setItemText(6, _translate("MainWindow", "Sensor 6"))
        self.combo_graph_sensors.setItemText(7, _translate("MainWindow", "Sensor 7"))
        self.combo_graph_sensors.setItemText(8, _translate("MainWindow", "Sensor 8"))
        self.combo_graph_sensors.setItemText(9, _translate("MainWindow", "Sensor 9"))
        self.button_graph_load.setText(_translate("MainWindow", " Load Graph"))
        self.frame_graph_crllabel2.setText(_translate("MainWindow", "Surface Gating App"))
        self.frame_graph_crllabel1.setText(_translate("MainWindow", "For Education Purposes Only"))
        self.frame_graph_crllabel3.setText(_translate("MainWindow", "All Rights Reserved"))
        self.label_graph_main.setText(_translate("MainWindow", "Main Graph"))
        self.label_graph_average.setText(_translate("MainWindow", "Average Graph"))
        self.label_graph_sensor.setText(_translate("MainWindow", "Sensor Graph"))
        self.button_graph_start.setText(_translate("MainWindow", "Start"))
        self.button_graph_stop.setText(_translate("MainWindow", "Reset"))
        self.button_graph_save.setText(_translate("MainWindow", "Save"))
        self.label_graph_id.setText(_translate("MainWindow", "ID : 1"))
        self.label_graph_name.setText(_translate("MainWindow", "Nama : Username"))
        self.label_graph_gender.setText(_translate("MainWindow", "Jenis Kelamin : Laki-laki"))
        self.label_graph_umur.setText(_translate("MainWindow", "Usia : 20"))
        self.label_graph_max.setText(_translate("MainWindow", "Max : 100 mm"))
        self.label_graph_min.setText(_translate("MainWindow", "Min : 2 mm"))
        self.label_graph_avg.setText(_translate("MainWindow", "Average : 51 mm"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
