# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import json
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    stackedMenu = {"winmenu_main": 0, "winmenu_login": 1, "winmenu_signup": 2, "winmenu_database": 3, "winmenu_graph": 4}

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(588, 458)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(600, 480))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint, True)
        MainWindow.setStyleSheet("QGraphicsView { border-radius: 10px; }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777214))
        self.stackedWidget.setBaseSize(QtCore.QSize(0, 0))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setStyleSheet("*{\n"
"    color: #fff;\n"
"    font-family: \'Trebuchet MS\';\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"*[objectName *= \"winmenu_\"]{\n"
"    border-image : url(:/icons/background_1.jpg);\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.48, stop:0 rgba(0, 100,180, 200), stop:1 rgba(0, 100, 115, 123));\n"
"}\n"
"QPushButton{\n"
"    padding: 10px;\n"
"    background-color: rgba(61, 80, 95, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"[objectName *= \"_head\"] QPushButton{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(120, 157, 186);\n"
"}\n"
"[objectName *= \"_setting\"], #frame_graph_title{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/*For All Header*/\n"
"*[objectName*=\"_head\"]{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"*[objectName*=\"edit\"]{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:2px solid rgba(255, 255, 255, 155);\n"
"    color:rgba(255,255,255,250);\n"
"    selection-color:rgba(50,50,50,250);\n"
"    padding-bottom:7px;\n"
"}\n"
"\n"
"/*For Graph Container*/\n"
"#frame_graph_graph QStackedWidget>QWidget, #frame_graph_left{\n"
"}\n"
"#frame_graph_graph{\n"
"    background-color:rgba(0,0,0,0);\n"
"}\n"
"\n"
"/*DataBase Window*/\n"
"QTableWidget{\n"
"    background-color: rgba(0,0,0,100);\n"
"    alternate-background-color: rgb(75, 105, 117, 100);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgba(139, 193, 212, 100);\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    color: rgb(60, 124, 149);\n"
"    background-color: rgb(60, 124, 149);\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: rgba(0, 0, 0, 100);\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"    background-color: rgba(61, 80, 95, 100);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    color: rgb(60, 124, 149);\n"
"    background-color: rgb(29, 101, 129);\n"
"    margin: 3px 0px 3px 0px;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    color: rgb(60, 124, 149);\n"
"    background-color: rgb(29, 101, 129);\n"
"    margin: 3px 0px 3px 0px;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on{\n"
"    color: rgb(60, 124, 149);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on{\n"
"    color: rgb(60, 124, 149);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"QHeaderView{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-bottom-color: rgb(0, 0, 0);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 50));\n"
"    padding: 4px;\n"
"    font-size: 14pt;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(0, 0, 0);\n"
"    border-right: 1px solid #000000;\n"
"}\n"
"\n"
"/*Login Window*/\n"
"#widget_login_logform{\n"
"    align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-bottom-right-radius:25px;\n"
"}\n"
"#button_login_log:hover{\n"
"    align: center;\n"
"    background-color: rgb(48, 92, 123);\n"
"    width: 75px;\n"
"}\n"
"#widget_login_decor{\n"
"    border-image : url(:/icons/background_1.jpg);\n"
"}\n"
"\n"
"/*SIgnup Window*/\n"
"#widget_signup_form{\n"
"    align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"    border-bottom-right-radius:25px;\n"
"}\n"
"#widget_signup_form QComboBox{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#widget_signup_form QComboBox QAbstractItemView{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(50, 150,200, 235), stop:1 rgba(235, 255, 255, 155));\n"
"}\n"
"#label_signup_gender{\n"
"    color: rgba(255, 255, 255, 255);\n"
"}\n"
"#button_signup_sign{\n"
"    align: center;\n"
"    background-color: rgb(48, 92, 123, 100);\n"
"    width: 75px;\n"
"}\n"
"#button_signup_sign:hover{\n"
"    align: center;\n"
"    background-color: rgb(48, 92, 123, 255);\n"
"    width: 75px;\n"
"}\n"
"\n"
"#frame_graph_gbframe QComboBox{\n"
"text-align: center;\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"#frame_graph_gbframe QComboBox QAbstractItemView::item:hover {"
"    background-color: rgba(61, 80, 95, 100);"
"}"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.winmenu_main = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.winmenu_main.sizePolicy().hasHeightForWidth())
        self.winmenu_main.setSizePolicy(sizePolicy)
        self.winmenu_main.setSizeIncrement(QtCore.QSize(1, 1))
        self.winmenu_main.setAutoFillBackground(False)
        self.winmenu_main.setStyleSheet("#main_menu{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.48, stop:0 rgba(0, 100,180, 200), stop:1 rgba(0, 100, 115, 123));\n"
"}\n"
"#button_main_login,\n"
"#button_main_signup,\n"
"#button_main_database,\n"
"#label_main_mainlabel{\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"color: rgba(255,255,255,255);\n"
"background-color: rgba(33, 43, 51, 100);\n"
"}\n"
"#button_main_login::hover,\n"
"#button_main_signup::hover,\n"
"#button_main_database::hover{\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"color: rgba(255,255,255,255);\n"
"background-color: rgba(33, 43, 51, 255);\n"
"}")
        self.winmenu_main.setObjectName("winmenu_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.winmenu_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_main_head = QtWidgets.QFrame(self.winmenu_main)
        self.frame_main_head.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_main_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_head.setObjectName("frame_main_head")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.frame_main_head)
        self.horizontalLayout_39.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.frame_main_menu = QtWidgets.QFrame(self.frame_main_head)
        self.frame_main_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_menu.setObjectName("frame_main_menu")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.frame_main_menu)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.button_main_menu = QtWidgets.QPushButton(self.frame_main_menu)
        self.button_main_menu.setMaximumSize(QtCore.QSize(30, 30))
        self.button_main_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/menu-bar-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_main_menu.setIcon(icon)
        self.button_main_menu.setIconSize(QtCore.QSize(30, 30))
        self.button_main_menu.setObjectName("button_main_menu")
        self.horizontalLayout_40.addWidget(self.button_main_menu)
        self.label_main_menu = QtWidgets.QLabel(self.frame_main_menu)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_main_menu.setFont(font)
        self.label_main_menu.setObjectName("label_main_menu")
        self.horizontalLayout_40.addWidget(self.label_main_menu)
        self.horizontalLayout_39.addWidget(self.frame_main_menu, 0, QtCore.Qt.AlignLeft)
        self.frame_main_dash = QtWidgets.QFrame(self.frame_main_head)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.frame_main_dash.setFont(font)
        self.frame_main_dash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_dash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_dash.setObjectName("frame_main_dash")
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout(self.frame_main_dash)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_main_dash = QtWidgets.QLabel(self.frame_main_dash)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_main_dash.setFont(font)
        self.label_main_dash.setObjectName("label_main_dash")
        self.horizontalLayout_41.addWidget(self.label_main_dash)
        self.horizontalLayout_39.addWidget(self.frame_main_dash, 0, QtCore.Qt.AlignHCenter)
        self.frame_main_ctrl = QtWidgets.QFrame(self.frame_main_head)
        self.frame_main_ctrl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main_ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_ctrl.setObjectName("frame_main_ctrl")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout(self.frame_main_ctrl)
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_42.setSpacing(2)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.button_main_min = QtWidgets.QPushButton(self.frame_main_ctrl)
        self.button_main_min.setMinimumSize(QtCore.QSize(30, 30))
        self.button_main_min.setMaximumSize(QtCore.QSize(30, 30))
        self.button_main_min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus-sign-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_main_min.setIcon(icon1)
        self.button_main_min.setObjectName("button_main_min")
        self.horizontalLayout_42.addWidget(self.button_main_min)
        self.button_main_size = QtWidgets.QPushButton(self.frame_main_ctrl)
        self.button_main_size.setMinimumSize(QtCore.QSize(30, 30))
        self.button_main_size.setMaximumSize(QtCore.QSize(30, 30))
        self.button_main_size.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/aspect-ratio-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_main_size.setIcon(icon2)
        self.button_main_size.setObjectName("button_main_size")
        self.horizontalLayout_42.addWidget(self.button_main_size)
        self.button_main_exit = QtWidgets.QPushButton(self.frame_main_ctrl)
        self.button_main_exit.setMinimumSize(QtCore.QSize(30, 30))
        self.button_main_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.button_main_exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/close-window-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_main_exit.setIcon(icon3)
        self.button_main_exit.setObjectName("button_main_exit")
        self.horizontalLayout_42.addWidget(self.button_main_exit)
        self.horizontalLayout_39.addWidget(self.frame_main_ctrl, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_main_head)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_main_mainlabel = QtWidgets.QLabel(self.winmenu_main)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_main_mainlabel.setFont(font)
        self.label_main_mainlabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_main_mainlabel.setLineWidth(0)
        self.label_main_mainlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_main_mainlabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_main_mainlabel.setObjectName("label_main_mainlabel")
        self.gridLayout.addWidget(self.label_main_mainlabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.button_main_login = QtWidgets.QPushButton(self.winmenu_main)
        self.button_main_login.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_main_login.sizePolicy().hasHeightForWidth())
        self.button_main_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.button_main_login.setFont(font)
        self.button_main_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_main_login.setObjectName("button_main_login")
        self.gridLayout.addWidget(self.button_main_login, 2, 1, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 6, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 6, 0, 1, 1)
        self.button_main_signup = QtWidgets.QPushButton(self.winmenu_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_main_signup.sizePolicy().hasHeightForWidth())
        self.button_main_signup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.button_main_signup.setFont(font)
        self.button_main_signup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_main_signup.setObjectName("button_main_signup")
        self.gridLayout.addWidget(self.button_main_signup, 6, 1, 1, 1)
        self.button_main_database = QtWidgets.QPushButton(self.winmenu_main)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.button_main_database.setFont(font)
        self.button_main_database.setObjectName("button_main_database")
        self.gridLayout.addWidget(self.button_main_database, 8, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem7, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 130, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.stackedWidget.addWidget(self.winmenu_main)
        self.winmenu_login = QtWidgets.QWidget()
        self.winmenu_login.setObjectName("winmenu_login")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.winmenu_login)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_login_head = QtWidgets.QFrame(self.winmenu_login)
        self.frame_login_head.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_login_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_head.setObjectName("frame_login_head")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_login_head)
        self.horizontalLayout_26.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.frame_login_menu = QtWidgets.QFrame(self.frame_login_head)
        self.frame_login_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_menu.setObjectName("frame_login_menu")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.frame_login_menu)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.button_login_menu = QtWidgets.QPushButton(self.frame_login_menu)
        self.button_login_menu.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_menu.setText("")
        self.button_login_menu.setIcon(icon)
        self.button_login_menu.setIconSize(QtCore.QSize(30, 30))
        self.button_login_menu.setObjectName("button_login_menu")
        self.horizontalLayout_47.addWidget(self.button_login_menu)
        self.label_login_menu = QtWidgets.QLabel(self.frame_login_menu)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_login_menu.setFont(font)
        self.label_login_menu.setObjectName("label_login_menu")
        self.horizontalLayout_47.addWidget(self.label_login_menu)
        self.horizontalLayout_26.addWidget(self.frame_login_menu, 0, QtCore.Qt.AlignLeft)
        self.frame_login_dash = QtWidgets.QFrame(self.frame_login_head)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.frame_login_dash.setFont(font)
        self.frame_login_dash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_dash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_dash.setObjectName("frame_login_dash")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.frame_login_dash)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_login_dash = QtWidgets.QLabel(self.frame_login_dash)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_login_dash.setFont(font)
        self.label_login_dash.setObjectName("label_login_dash")
        self.horizontalLayout_48.addWidget(self.label_login_dash)
        self.horizontalLayout_26.addWidget(self.frame_login_dash, 0, QtCore.Qt.AlignHCenter)
        self.frame_login_ctrl = QtWidgets.QFrame(self.frame_login_head)
        self.frame_login_ctrl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_ctrl.setObjectName("frame_login_ctrl")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout(self.frame_login_ctrl)
        self.horizontalLayout_49.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_49.setSpacing(2)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.button_login_min = QtWidgets.QPushButton(self.frame_login_ctrl)
        self.button_login_min.setMinimumSize(QtCore.QSize(30, 30))
        self.button_login_min.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_min.setText("")
        self.button_login_min.setIcon(icon1)
        self.button_login_min.setObjectName("button_login_min")
        self.horizontalLayout_49.addWidget(self.button_login_min)
        self.button_login_size = QtWidgets.QPushButton(self.frame_login_ctrl)
        self.button_login_size.setMinimumSize(QtCore.QSize(30, 30))
        self.button_login_size.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_size.setText("")
        self.button_login_size.setIcon(icon2)
        self.button_login_size.setObjectName("button_login_size")
        self.horizontalLayout_49.addWidget(self.button_login_size)
        self.button_login_exit = QtWidgets.QPushButton(self.frame_login_ctrl)
        self.button_login_exit.setMinimumSize(QtCore.QSize(30, 30))
        self.button_login_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.button_login_exit.setText("")
        self.button_login_exit.setIcon(icon3)
        self.button_login_exit.setObjectName("button_login_exit")
        self.horizontalLayout_49.addWidget(self.button_login_exit)
        self.horizontalLayout_26.addWidget(self.frame_login_ctrl, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.frame_login_head)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem9)
        self.layout_login_box = QtWidgets.QHBoxLayout()
        self.layout_login_box.setSpacing(0)
        self.layout_login_box.setObjectName("layout_login_box")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_login_box.addItem(spacerItem10)
        self.widget_login_decor = QtWidgets.QWidget(self.winmenu_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_login_decor.sizePolicy().hasHeightForWidth())
        self.widget_login_decor.setSizePolicy(sizePolicy)
        self.widget_login_decor.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_login_decor.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_login_decor.setObjectName("widget_login_decor")
        self.layout_login_box.addWidget(self.widget_login_decor)
        self.widget_login_logform = QtWidgets.QWidget(self.winmenu_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_login_logform.sizePolicy().hasHeightForWidth())
        self.widget_login_logform.setSizePolicy(sizePolicy)
        self.widget_login_logform.setMinimumSize(QtCore.QSize(200, 300))
        self.widget_login_logform.setObjectName("widget_login_logform")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_login_logform)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 3, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 9, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem13, 14, 0, 1, 1)
        self.edit_login_id = QtWidgets.QLineEdit(self.widget_login_logform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_login_id.sizePolicy().hasHeightForWidth())
        self.edit_login_id.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.edit_login_id.setFont(font)
        self.edit_login_id.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(255, 255, 255, 155);\n"
"\n"
"color:rgba(50,50,50,250);\n"
"padding-bottom:7px;\n"
"")
        self.edit_login_id.setObjectName("edit_login_id")
        self.gridLayout_3.addWidget(self.edit_login_id, 10, 0, 1, 1)
        self.label_login_title = QtWidgets.QLabel(self.widget_login_logform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_login_title.sizePolicy().hasHeightForWidth())
        self.label_login_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_login_title.setFont(font)
        self.label_login_title.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_login_title.setObjectName("label_login_title")
        self.gridLayout_3.addWidget(self.label_login_title, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem14, 11, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem15, 17, 0, 1, 1)
        self.button_login_sign = QtWidgets.QPushButton(self.widget_login_logform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_login_sign.sizePolicy().hasHeightForWidth())
        self.button_login_sign.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.button_login_sign.setFont(font)
        self.button_login_sign.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_login_sign.setObjectName("button_login_sign")
        self.gridLayout_3.addWidget(self.button_login_sign, 16, 0, 1, 1)
        self.button_login_log = QtWidgets.QPushButton(self.widget_login_logform)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_login_log.sizePolicy().hasHeightForWidth())
        self.button_login_log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.button_login_log.setFont(font)
        self.button_login_log.setObjectName("button_login_log")
        self.gridLayout_3.addWidget(self.button_login_log, 12, 0, 1, 1)
        self.layout_login_box.addWidget(self.widget_login_logform)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_login_box.addItem(spacerItem16)
        self.verticalLayout_4.addLayout(self.layout_login_box)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem17)
        self.stackedWidget.addWidget(self.winmenu_login)
        self.winmenu_signup = QtWidgets.QWidget()
        self.winmenu_signup.setObjectName("winmenu_signup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.winmenu_signup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_signup_head = QtWidgets.QFrame(self.winmenu_signup)
        self.frame_signup_head.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_signup_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_head.setObjectName("frame_signup_head")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.frame_signup_head)
        self.horizontalLayout_43.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.frame_signup_menu = QtWidgets.QFrame(self.frame_signup_head)
        self.frame_signup_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_menu.setObjectName("frame_signup_menu")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout(self.frame_signup_menu)
        self.horizontalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.button_signup_menu = QtWidgets.QPushButton(self.frame_signup_menu)
        self.button_signup_menu.setMaximumSize(QtCore.QSize(30, 30))
        self.button_signup_menu.setText("")
        self.button_signup_menu.setIcon(icon)
        self.button_signup_menu.setIconSize(QtCore.QSize(30, 30))
        self.button_signup_menu.setObjectName("button_signup_menu")
        self.horizontalLayout_50.addWidget(self.button_signup_menu)
        self.label_signup_menu = QtWidgets.QLabel(self.frame_signup_menu)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_signup_menu.setFont(font)
        self.label_signup_menu.setObjectName("label_signup_menu")
        self.horizontalLayout_50.addWidget(self.label_signup_menu)
        self.horizontalLayout_43.addWidget(self.frame_signup_menu, 0, QtCore.Qt.AlignLeft)
        self.frame_signup_dash = QtWidgets.QFrame(self.frame_signup_head)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.frame_signup_dash.setFont(font)
        self.frame_signup_dash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_dash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_dash.setObjectName("frame_signup_dash")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.frame_signup_dash)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_signup_dash = QtWidgets.QLabel(self.frame_signup_dash)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_signup_dash.setFont(font)
        self.label_signup_dash.setObjectName("label_signup_dash")
        self.horizontalLayout_51.addWidget(self.label_signup_dash)
        self.horizontalLayout_43.addWidget(self.frame_signup_dash, 0, QtCore.Qt.AlignHCenter)
        self.frame_signup_ctrl = QtWidgets.QFrame(self.frame_signup_head)
        self.frame_signup_ctrl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_signup_ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_signup_ctrl.setObjectName("frame_signup_ctrl")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.frame_signup_ctrl)
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_52.setSpacing(2)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.button_signup_min = QtWidgets.QPushButton(self.frame_signup_ctrl)
        self.button_signup_min.setMinimumSize(QtCore.QSize(30, 30))
        self.button_signup_min.setMaximumSize(QtCore.QSize(30, 30))
        self.button_signup_min.setText("")
        self.button_signup_min.setIcon(icon1)
        self.button_signup_min.setObjectName("button_signup_min")
        self.horizontalLayout_52.addWidget(self.button_signup_min)
        self.button_signup_size = QtWidgets.QPushButton(self.frame_signup_ctrl)
        self.button_signup_size.setMinimumSize(QtCore.QSize(30, 30))
        self.button_signup_size.setMaximumSize(QtCore.QSize(30, 30))
        self.button_signup_size.setText("")
        self.button_signup_size.setIcon(icon2)
        self.button_signup_size.setObjectName("button_signup_size")
        self.horizontalLayout_52.addWidget(self.button_signup_size)
        self.button_signup_exit = QtWidgets.QPushButton(self.frame_signup_ctrl)
        self.button_signup_exit.setMinimumSize(QtCore.QSize(30, 30))
        self.button_signup_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.button_signup_exit.setText("")
        self.button_signup_exit.setIcon(icon3)
        self.button_signup_exit.setObjectName("button_signup_exit")
        self.horizontalLayout_52.addWidget(self.button_signup_exit)
        self.horizontalLayout_43.addWidget(self.frame_signup_ctrl, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.frame_signup_head)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem18)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem19 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.label_signup_antiglare = QtWidgets.QLabel(self.winmenu_signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_signup_antiglare.sizePolicy().hasHeightForWidth())
        self.label_signup_antiglare.setSizePolicy(sizePolicy)
        self.label_signup_antiglare.setMinimumSize(QtCore.QSize(100, 0))
        self.label_signup_antiglare.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_signup_antiglare.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.72, stop:0 rgba(0, 0, 0, 20), stop:1 rgba(0,0,0,55));\n"
"border-top-left-radius:25px;")
        self.label_signup_antiglare.setText("")
        self.label_signup_antiglare.setObjectName("label_signup_antiglare")
        self.horizontalLayout_2.addWidget(self.label_signup_antiglare)
        self.widget_signup_form = QtWidgets.QWidget(self.winmenu_signup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_signup_form.sizePolicy().hasHeightForWidth())
        self.widget_signup_form.setSizePolicy(sizePolicy)
        self.widget_signup_form.setMinimumSize(QtCore.QSize(200, 300))
        self.widget_signup_form.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_signup_form.setBaseSize(QtCore.QSize(200, 0))
        self.widget_signup_form.setObjectName("widget_signup_form")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_signup_form)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.label_signup_label1 = QtWidgets.QLabel(self.widget_signup_form)
        self.label_signup_label1.setMinimumSize(QtCore.QSize(0, 40))
        self.label_signup_label1.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_signup_label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_signup_label1.setObjectName("label_signup_label1")
        self.verticalLayout_5.addWidget(self.label_signup_label1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem21)
        self.edit_signup_id = QtWidgets.QLineEdit(self.widget_signup_form)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.edit_signup_id.setFont(font)
        self.edit_signup_id.setText("")
        self.edit_signup_id.setObjectName("edit_signup_id")
        self.verticalLayout_5.addWidget(self.edit_signup_id)
        self.edit_signup_name = QtWidgets.QLineEdit(self.widget_signup_form)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.edit_signup_name.setFont(font)
        self.edit_signup_name.setObjectName("edit_signup_name")
        self.verticalLayout_5.addWidget(self.edit_signup_name)
        self.edit_signup_age = QtWidgets.QLineEdit(self.widget_signup_form)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.edit_signup_age.setFont(font)
        self.edit_signup_age.setText("")
        self.edit_signup_age.setObjectName("edit_signup_age")
        self.verticalLayout_5.addWidget(self.edit_signup_age)
        self.label_signup_gender = QtWidgets.QLabel(self.widget_signup_form)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_signup_gender.setFont(font)
        self.label_signup_gender.setObjectName("label_signup_gender")
        self.verticalLayout_5.addWidget(self.label_signup_gender)
        self.combobox_signup_gender = QtWidgets.QComboBox(self.widget_signup_form)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.combobox_signup_gender.setFont(font)
        self.combobox_signup_gender.setObjectName("combobox_signup_gender")
        self.combobox_signup_gender.addItem("")
        self.combobox_signup_gender.addItem("")
        self.verticalLayout_5.addWidget(self.combobox_signup_gender)
        spacerItem22 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem22)
        self.button_signup_sign = QtWidgets.QPushButton(self.widget_signup_form)
        self.button_signup_sign.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_signup_sign.sizePolicy().hasHeightForWidth())
        self.button_signup_sign.setSizePolicy(sizePolicy)
        self.button_signup_sign.setObjectName("button_signup_sign")
        self.verticalLayout_5.addWidget(self.button_signup_sign)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem23)
        self.horizontalLayout_2.addWidget(self.widget_signup_form)
        spacerItem24 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem24)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem25)
        self.stackedWidget.addWidget(self.winmenu_signup)
        self.winmenu_database = QtWidgets.QWidget()
        self.winmenu_database.setObjectName("winmenu_database")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.winmenu_database)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_database_head = QtWidgets.QFrame(self.winmenu_database)
        self.frame_database_head.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_database_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_head.setObjectName("frame_database_head")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_database_head)
        self.horizontalLayout_35.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.frame_database_menu = QtWidgets.QFrame(self.frame_database_head)
        self.frame_database_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_menu.setObjectName("frame_database_menu")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_database_menu)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.button_database_menu = QtWidgets.QPushButton(self.frame_database_menu)
        self.button_database_menu.setMaximumSize(QtCore.QSize(30, 30))
        self.button_database_menu.setText("")
        self.button_database_menu.setIcon(icon)
        self.button_database_menu.setIconSize(QtCore.QSize(30, 30))
        self.button_database_menu.setObjectName("button_database_menu")
        self.horizontalLayout_36.addWidget(self.button_database_menu)
        self.label_database_menu = QtWidgets.QLabel(self.frame_database_menu)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_database_menu.setFont(font)
        self.label_database_menu.setObjectName("label_database_menu")
        self.horizontalLayout_36.addWidget(self.label_database_menu)
        self.horizontalLayout_35.addWidget(self.frame_database_menu, 0, QtCore.Qt.AlignLeft)
        self.frame_database_dash = QtWidgets.QFrame(self.frame_database_head)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.frame_database_dash.setFont(font)
        self.frame_database_dash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_dash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_dash.setObjectName("frame_database_dash")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.frame_database_dash)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_database_dash = QtWidgets.QLabel(self.frame_database_dash)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_database_dash.setFont(font)
        self.label_database_dash.setObjectName("label_database_dash")
        self.horizontalLayout_37.addWidget(self.label_database_dash)
        self.horizontalLayout_35.addWidget(self.frame_database_dash, 0, QtCore.Qt.AlignHCenter)
        self.frame_database_ctrl = QtWidgets.QFrame(self.frame_database_head)
        self.frame_database_ctrl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_database_ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_database_ctrl.setObjectName("frame_database_ctrl")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.frame_database_ctrl)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setSpacing(2)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.button_database_min = QtWidgets.QPushButton(self.frame_database_ctrl)
        self.button_database_min.setMinimumSize(QtCore.QSize(30, 30))
        self.button_database_min.setMaximumSize(QtCore.QSize(30, 30))
        self.button_database_min.setText("")
        self.button_database_min.setIcon(icon1)
        self.button_database_min.setObjectName("button_database_min")
        self.horizontalLayout_38.addWidget(self.button_database_min)
        self.button_database_size = QtWidgets.QPushButton(self.frame_database_ctrl)
        self.button_database_size.setMinimumSize(QtCore.QSize(30, 30))
        self.button_database_size.setMaximumSize(QtCore.QSize(30, 30))
        self.button_database_size.setText("")
        self.button_database_size.setIcon(icon2)
        self.button_database_size.setCheckable(True)
        self.button_database_size.setObjectName("button_database_size")
        self.horizontalLayout_38.addWidget(self.button_database_size)
        self.button_database_exit = QtWidgets.QPushButton(self.frame_database_ctrl)
        self.button_database_exit.setMinimumSize(QtCore.QSize(30, 30))
        self.button_database_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.button_database_exit.setText("")
        self.button_database_exit.setIcon(icon3)
        self.button_database_exit.setObjectName("button_database_exit")
        self.horizontalLayout_38.addWidget(self.button_database_exit)
        self.horizontalLayout_35.addWidget(self.frame_database_ctrl, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_database_head)
        self.table_database_data = QtWidgets.QTableWidget(self.winmenu_database)
        self.table_database_data.setFrameShape(QtWidgets.QFrame.VLine)
        self.table_database_data.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table_database_data.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table_database_data.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table_database_data.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_database_data.setAutoScroll(True)
        self.table_database_data.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_database_data.setAlternatingRowColors(True)
        self.table_database_data.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_database_data.setTextElideMode(QtCore.Qt.ElideLeft)
        self.table_database_data.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_database_data.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_database_data.setRowCount(15)
        self.table_database_data.setObjectName("table_database_data")
        self.table_database_data.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_database_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_database_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_database_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_database_data.setHorizontalHeaderItem(3, item)
        self.table_database_data.horizontalHeader().setCascadingSectionResizes(False)
        self.table_database_data.horizontalHeader().setSortIndicatorShown(True)
        self.table_database_data.horizontalHeader().setStretchLastSection(False)
        self.table_database_data.verticalHeader().setVisible(False)
        self.table_database_data.verticalHeader().setCascadingSectionResizes(False)
        self.table_database_data.verticalHeader().setSortIndicatorShown(False)
        header = self.table_database_data.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Interactive)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Interactive)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.Interactive)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.Interactive)
        header.resizeSection(0, int((self.geometry().width() - 40)/4))
        header.resizeSection(1, int((self.geometry().width() - 40)/4))
        header.resizeSection(2, int((self.geometry().width() - 40)/4))
        header.resizeSection(3, int((self.geometry().width() - 40)/4))
        self.verticalLayout_2.addWidget(self.table_database_data)
        self.stackedWidget.addWidget(self.winmenu_database)
        self.winmenu_graph = QtWidgets.QWidget()
        self.winmenu_graph.setStyleSheet("")
        self.winmenu_graph.setObjectName("winmenu_graph")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.winmenu_graph)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.layout_graph_h1 = QtWidgets.QHBoxLayout()
        self.layout_graph_h1.setObjectName("layout_graph_h1")
        self.frame_graph_left = QtWidgets.QFrame(self.winmenu_graph)
        self.frame_graph_left.setObjectName("frame_graph_left")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_graph_left)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_graph_title = QtWidgets.QFrame(self.frame_graph_left)
        self.frame_graph_title.setMinimumSize(QtCore.QSize(200, 80))
        self.frame_graph_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_title.setObjectName("frame_graph_title")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_graph_title)
        self.horizontalLayout_19.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_graph_ticon = QtWidgets.QLabel(self.frame_graph_title)
        self.label_graph_ticon.setMinimumSize(QtCore.QSize(40, 40))
        self.label_graph_ticon.setMaximumSize(QtCore.QSize(40, 40))
        self.label_graph_ticon.setText("")
        self.label_graph_ticon.setPixmap(QtGui.QPixmap(":/icons/icons/bar-chart-icon.svg"))
        self.label_graph_ticon.setScaledContents(True)
        self.label_graph_ticon.setObjectName("label_graph_ticon")
        self.horizontalLayout_19.addWidget(self.label_graph_ticon, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_graph_tlabel = QtWidgets.QLabel(self.frame_graph_title)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_graph_tlabel.setFont(font)
        self.label_graph_tlabel.setObjectName("label_graph_tlabel")
        self.horizontalLayout_19.addWidget(self.label_graph_tlabel, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_16.addWidget(self.frame_graph_title, 0, QtCore.Qt.AlignTop)
        self.frame_graph_gbframe = QtWidgets.QFrame(self.frame_graph_left)
        self.frame_graph_gbframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_gbframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_gbframe.setObjectName("frame_graph_gbframe")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_graph_gbframe)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.button_graph_gbutton = QtWidgets.QPushButton(self.frame_graph_gbframe)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.button_graph_gbutton.setFont(font)
        icon = QtGui.QIcon.fromTheme("SP_ArrowBack")
        self.button_graph_gbutton.setIcon(icon)
        self.button_graph_gbutton.setObjectName("button_graph_gbutton")
        self.verticalLayout_17.addWidget(self.button_graph_gbutton)
        self.button_graph_avbbutton = QtWidgets.QPushButton(self.frame_graph_gbframe)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.button_graph_avbbutton.setFont(font)
        self.button_graph_avbbutton.setObjectName("button_graph_avbbutton")
        self.verticalLayout_17.addWidget(self.button_graph_avbbutton)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.button_graph_setting = QtWidgets.QPushButton(self.frame_graph_gbframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_graph_setting.sizePolicy().hasHeightForWidth())
        self.button_graph_setting.setSizePolicy(sizePolicy)
        self.button_graph_setting.setMinimumSize(QtCore.QSize(40, 60))
        self.button_graph_setting.setMaximumSize(QtCore.QSize(200, 50))
        self.combo_graph_sensors = QtWidgets.QComboBox(self.frame_graph_gbframe)
        self.combo_graph_sensors.setStyleSheet("QComboBox QAbstractItemView::item:hover {\n""    background-color: black;\n"
                                                "}\n"
                                                "QComboBox::down-arrow {\n"
                                                "    color: black;\n"
                                                "}\n"
                                                "QComboBox {\n"
                                                "    text-align: center;\n"
                                                "}\n"
                                                "")
        self.combo_graph_sensors.setEditable(False)
        self.combo_graph_sensors.setObjectName("combo_graph_sensors")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.combo_graph_sensors.addItem("")
        self.verticalLayout_17.addWidget(self.combo_graph_sensors)
        self.verticalLayout_17.addItem(spacerItem26)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/engine-gears-icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_graph_setting.setIcon(icon4)
        self.button_graph_setting.setObjectName("button_graph_setting")
        self.verticalLayout_17.addWidget(self.button_graph_setting)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem27)
        self.verticalLayout_16.addWidget(self.frame_graph_gbframe)
        self.frame_graph_crlframe = QtWidgets.QFrame(self.frame_graph_left)
        self.frame_graph_crlframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_crlframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_crlframe.setObjectName("frame_graph_crlframe")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_graph_crlframe)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_graph_crlabel1 = QtWidgets.QLabel(self.frame_graph_crlframe)
        self.label_graph_crlabel1.setObjectName("label_graph_crlabel1")
        self.verticalLayout_18.addWidget(self.label_graph_crlabel1)
        self.label_graph_crlabel2 = QtWidgets.QLabel(self.frame_graph_crlframe)
        self.label_graph_crlabel2.setObjectName("label_graph_crlabel2")
        self.verticalLayout_18.addWidget(self.label_graph_crlabel2)
        self.label_graph_crlabel3 = QtWidgets.QLabel(self.frame_graph_crlframe)
        self.label_graph_crlabel3.setObjectName("label_graph_crlabel3")
        self.verticalLayout_18.addWidget(self.label_graph_crlabel3)
        self.verticalLayout_16.addWidget(self.frame_graph_crlframe)
        self.layout_graph_h1.addWidget(self.frame_graph_left)
        self.frame_graph_right = QtWidgets.QFrame(self.winmenu_graph)
        self.frame_graph_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_right.setObjectName("frame_graph_right")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_graph_right)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_graph_head = QtWidgets.QFrame(self.frame_graph_right)
        self.frame_graph_head.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_graph_head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_head.setObjectName("frame_graph_head")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_graph_head)
        self.horizontalLayout_23.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.frame_graph_menu = QtWidgets.QFrame(self.frame_graph_head)
        self.frame_graph_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_menu.setObjectName("frame_graph_menu")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_graph_menu)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.button_graph_menu = QtWidgets.QPushButton(self.frame_graph_menu)
        self.button_graph_menu.setMaximumSize(QtCore.QSize(30, 30))
        self.button_graph_menu.setText("")
        self.button_graph_menu.setIcon(icon)
        self.button_graph_menu.setIconSize(QtCore.QSize(30, 30))
        self.button_graph_menu.setObjectName("button_graph_menu")
        self.horizontalLayout_24.addWidget(self.button_graph_menu)
        self.label_graph_menu = QtWidgets.QLabel(self.frame_graph_menu)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_graph_menu.setFont(font)
        self.label_graph_menu.setObjectName("label_graph_menu")
        self.horizontalLayout_24.addWidget(self.label_graph_menu)
        self.horizontalLayout_23.addWidget(self.frame_graph_menu, 0, QtCore.Qt.AlignLeft)
        self.frame_graph_dash = QtWidgets.QFrame(self.frame_graph_head)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.frame_graph_dash.setFont(font)
        self.frame_graph_dash.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_dash.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_dash.setObjectName("frame_graph_dash")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_graph_dash)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_graph_dash = QtWidgets.QLabel(self.frame_graph_dash)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_graph_dash.setFont(font)
        self.label_graph_dash.setObjectName("label_graph_dash")
        self.horizontalLayout_25.addWidget(self.label_graph_dash)
        self.horizontalLayout_23.addWidget(self.frame_graph_dash, 0, QtCore.Qt.AlignHCenter)
        self.frame_graph_ctrl = QtWidgets.QFrame(self.frame_graph_head)
        self.frame_graph_ctrl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_ctrl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_ctrl.setObjectName("frame_graph_ctrl")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_graph_ctrl)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(2)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.button_graph_min = QtWidgets.QPushButton(self.frame_graph_ctrl)
        self.button_graph_min.setMinimumSize(QtCore.QSize(30, 30))
        self.button_graph_min.setMaximumSize(QtCore.QSize(30, 30))
        self.button_graph_min.setText("")
        self.button_graph_min.setIcon(icon1)
        self.button_graph_min.setObjectName("button_graph_min")
        self.horizontalLayout_27.addWidget(self.button_graph_min)
        self.button_graph_size = QtWidgets.QPushButton(self.frame_graph_ctrl)
        self.button_graph_size.setMinimumSize(QtCore.QSize(30, 30))
        self.button_graph_size.setMaximumSize(QtCore.QSize(30, 30))
        self.button_graph_size.setText("")
        self.button_graph_size.setIcon(icon2)
        self.button_graph_size.setObjectName("button_graph_size")
        self.horizontalLayout_27.addWidget(self.button_graph_size)
        self.button_graph_exit = QtWidgets.QPushButton(self.frame_graph_ctrl)
        self.button_graph_exit.setMinimumSize(QtCore.QSize(30, 30))
        self.button_graph_exit.setMaximumSize(QtCore.QSize(30, 30))
        self.button_graph_exit.setText("")
        self.button_graph_exit.setIcon(icon3)
        self.button_graph_exit.setObjectName("button_graph_exit")
        self.horizontalLayout_27.addWidget(self.button_graph_exit)
        self.horizontalLayout_23.addWidget(self.frame_graph_ctrl, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_19.addWidget(self.frame_graph_head, 0, QtCore.Qt.AlignTop)
        self.frame_graph_graph = QtWidgets.QFrame(self.frame_graph_right)
        self.frame_graph_graph.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_graph.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_graph.setObjectName("frame_graph_graph")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_graph_graph)
        self.horizontalLayout_28.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.widget_graph_graph = QtWidgets.QStackedWidget(self.frame_graph_graph)
        self.widget_graph_graph.setObjectName("widget_graph_graph")
        self.main_graph_2 = QtWidgets.QWidget()
        self.main_graph_2.setObjectName("main_graph_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.main_graph_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_25 = QtWidgets.QFrame(self.main_graph_2)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_32 = QtWidgets.QLabel(self.frame_25)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_21.addWidget(self.label_32, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_20.addWidget(self.frame_25, 0, QtCore.Qt.AlignTop)
        self.frame_26 = QtWidgets.QFrame(self.main_graph_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_26.sizePolicy().hasHeightForWidth())
        self.frame_26.setSizePolicy(sizePolicy)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_20.addWidget(self.frame_26)
        self.widget_graph_graph.addWidget(self.main_graph_2)
        self.average_graph_2 = QtWidgets.QWidget()
        self.average_graph_2.setObjectName("average_graph_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.average_graph_2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_27 = QtWidgets.QFrame(self.average_graph_2)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_33 = QtWidgets.QLabel(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_23.addWidget(self.label_33, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_22.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.average_graph_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_28)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_22.addWidget(self.frame_28)
        self.widget_graph_graph.addWidget(self.average_graph_2)
        self.sensors_graph_2 = QtWidgets.QWidget()
        self.sensors_graph_2.setObjectName("sensors_graph_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.sensors_graph_2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_29 = QtWidgets.QFrame(self.sensors_graph_2)
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_34 = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_25.addWidget(self.label_34, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_24.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.sensors_graph_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_30.sizePolicy().hasHeightForWidth())
        self.frame_30.setSizePolicy(sizePolicy)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_30)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_24.addWidget(self.frame_30)
        self.widget_graph_graph.addWidget(self.sensors_graph_2)
        self.horizontalLayout_28.addWidget(self.widget_graph_graph)
        self.verticalLayout_19.addWidget(self.frame_graph_graph)
        self.frame_graph_util = QtWidgets.QFrame(self.frame_graph_right)
        self.frame_graph_util.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_graph_util.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_graph_util.setObjectName("frame_graph_util")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_graph_util)
        self.horizontalLayout_29.setContentsMargins(-1, 0, 11, -1)
        self.horizontalLayout_29.setSpacing(15)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.button_graph_start = QtWidgets.QPushButton(self.frame_graph_util)
        self.button_graph_start.setObjectName("button_graph_start")
        self.horizontalLayout_29.addWidget(self.button_graph_start)
        self.button_graph_stop = QtWidgets.QPushButton(self.frame_graph_util)
        self.button_graph_stop.setObjectName("button_graph_stop")
        self.horizontalLayout_29.addWidget(self.button_graph_stop)
        self.button_graph_save = QtWidgets.QPushButton(self.frame_graph_util)
        self.button_graph_save.setObjectName("button_graph_save")
        self.horizontalLayout_29.addWidget(self.button_graph_save)
        self.verticalLayout_19.addWidget(self.frame_graph_util)

        self.frame_graph_data = QtWidgets.QWidget(self.frame_graph_right)
        self.frame_graph_data.setObjectName("frame_graph_data")
        self.layout_graph_data = QtWidgets.QHBoxLayout(self.frame_graph_data)

        self.frame_graph_inleft = QtWidgets.QWidget(self.frame_graph_data)
        self.frame_graph_inright = QtWidgets.QWidget(self.frame_graph_data)
        self.frame_graph_inleft.setObjectName("frame_graph_inleft")
        self.frame_graph_inright.setObjectName("frame_graph_inright")
        self.layout_graph_inleft = QtWidgets.QVBoxLayout(self.frame_graph_inleft)
        self.layout_graph_inright = QtWidgets.QVBoxLayout(self.frame_graph_inright)
        self.layout_graph_data.addWidget(self.frame_graph_inleft)
        self.layout_graph_data.addWidget(self.frame_graph_inright)

        self.label_graph_id = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_id.setMinimumSize(QtCore.QSize(int(self.button_graph_stop.geometry().width() * 1.5), 0))
        self.label_graph_id.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_graph_id.setFont(font)
        self.label_graph_id.setObjectName("label_graph_id")

        self.label_graph_name = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_graph_name.setFont(font)
        self.label_graph_name.setObjectName("label_graph_name")

        self.label_graph_gender = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_gender.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_graph_gender.setFont(font)
        self.label_graph_gender.setObjectName("label_graph_gender")

        self.label_graph_age = QtWidgets.QLabel(self.frame_graph_inleft)
        self.label_graph_age.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(-1)
        self.label_graph_age.setFont(font)
        self.label_graph_age.setObjectName("label_graph_age")

        self.layout_graph_inleft.addWidget(self.label_graph_id)
        self.layout_graph_inleft.addWidget(self.label_graph_name)
        self.layout_graph_inleft.addWidget(self.label_graph_age)
        self.layout_graph_inleft.addWidget(self.label_graph_gender)

        self.label_graph_max = QtWidgets.QLabel(self.frame_graph_inright)
        self.label_graph_max.setObjectName("label_graph_max")
        self.label_graph_min = QtWidgets.QLabel(self.frame_graph_inright)
        self.label_graph_min.setObjectName("label_graph_min")
        self.label_graph_avg = QtWidgets.QLabel(self.frame_graph_inright)
        self.label_graph_avg.setObjectName("label_graph_avg")
        self.label_graph_rate = QtWidgets.QLabel(self.frame_graph_inright)
        self.label_graph_rate.setObjectName("label_graph_rate")

        self.layout_graph_inright.addWidget(self.label_graph_max)
        self.layout_graph_inright.addWidget(self.label_graph_min)
        self.layout_graph_inright.addWidget(self.label_graph_avg)
        self.layout_graph_inright.addWidget(self.label_graph_rate)

        self.verticalLayout_19.addWidget(self.frame_graph_data)
        self.layout_graph_h1.addWidget(self.frame_graph_right)
        self.verticalLayout_28.addLayout(self.layout_graph_h1)
        self.stackedWidget.addWidget(self.winmenu_graph)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.widget_graph_graph.setCurrentIndex(2)
        self.button_database_min.clicked.connect(MainWindow.showMinimized)
        self.button_database_size.clicked.connect(self.sizeUi)

        self.button_database_size.setCheckable(True)
        self.button_main_size.setCheckable(True)
        self.button_graph_size.setCheckable(True)
        self.button_login_size.setCheckable(True)
        self.button_signup_size.setCheckable(True)

        self.patient = {"age": 0, "gender": "", "id": "", "max": 0, "min": 0, "name": ""}

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # initialize all button in application
    def buttonInit(self):
        self.button_database_exit.clicked.connect(self.close)
        self.button_main_exit.clicked.connect(self.close)
        self.button_graph_exit.clicked.connect(self.close)
        self.button_login_exit.clicked.connect(self.close)
        self.button_signup_exit.clicked.connect(self.close)

        self.button_database_min.clicked.connect(self.showMinimized)
        self.button_main_min.clicked.connect(self.showMinimized)
        self.button_graph_min.clicked.connect(self.showMinimized)
        self.button_login_min.clicked.connect(self.showMinimized)
        self.button_signup_min.clicked.connect(self.showMinimized)

        self.button_database_size.clicked.connect(self.sizeUi)
        self.button_main_size.clicked.connect(self.sizeUi)
        self.button_graph_size.clicked.connect(self.sizeUi)
        self.button_login_size.clicked.connect(self.sizeUi)
        self.button_signup_size.clicked.connect(self.sizeUi)

        self.button_database_menu.clicked.connect(self.dropMenu)
        self.button_main_menu.clicked.connect(self.dropMenu)
        self.button_graph_menu.clicked.connect(self.dropMenu)
        self.button_login_menu.clicked.connect(self.dropMenu)
        self.button_signup_menu.clicked.connect(self.dropMenu)

        # for navigation
        self.button_main_login.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_login"]))
        self.button_main_signup.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_signup"]))
        self.button_login_sign.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_signup"]))
        self.button_main_database.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_database"]))
        self.button_main_database.clicked.connect(self.loadDatabase)
        
        self.button_login_log.clicked.connect(self.patientLog)
        self.button_signup_sign.clicked.connect(self.patientSign)

    # resize control button
    def sizeUi(self, checked):
        if checked:
                self.showMaximized() 
        else:
                self.showNormal()

    # dropdown menu
    def dropMenu(self):
        Menu = QtWidgets.QMenu(self)
        to_main = Menu.addAction("Main Menu")
        to_login = Menu.addAction("Login")
        to_signup = Menu.addAction("Signup")
        Menu.addSeparator()
        to_back = Menu.addAction("Back")
        to_exit = Menu.addAction("Exit")
        source = self.sender()
        action = Menu.exec_(source.mapToGlobal(QtCore.QPoint(source.geometry().x(),source.geometry().y()+source.geometry().height()))) 
        if action == to_main:
            self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_main"])
        elif action == to_login:
            self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_login"])
        elif action == to_signup:
            self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_signup"])
        elif action == to_back:
            if self.stackedWidget.currentIndex() == self.stackedMenu["winmenu_graph"]:
                self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_login"])
            elif self.stackedWidget.currentIndex() == self.stackedMenu["winmenu_main"]:
                pass
            else:
                self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_main"])
        elif action == to_exit:
            self.close()

    def popUp(self):
        center = QtCore.QPoint(int(self.geometry().x()+(self.geometry().width() / 2)), int(self.geometry().y()+(self.geometry().height() / 2)))
        msg = QtWidgets.QMessageBox()
        msg.setText("Message box pop up window")
        msg.setWindowTitle("QMessageBox Example")
        msg.setStandardButtons(QtWidgets.QMessageBox.Ok | QtWidgets.QMessageBox.Cancel)
        msg.move(center)
        msg.exec()  

    def loadDatabase(self):
        pass

    # get patient data from database when user try to 
    def patientLog(self):
        try:
            if not self.edit_login_id.text():
                self.popUp()
                return
            
            # # database
            # self.patient = self.db.getPatient(self.edit_login_text())
            # self.updateGraphLabel(self.patient)
            self.stackedWidget.setCurrentIndex(self.stackedMenu["winmenu_graph"])
        except:
            self.popUp() 

    def patientSign(self):
        try:
            if not(self.label_signup_id.text() or self.label_signup_name.text() or self.label_signup_age.text()):
                self.popUp()
                return

            # # database
            # self.patient["name"] = self.edit_signup_name.text()
            # self.patient["age"] = int(self.edit_signup_age.text())
            # self.patient["id"] = self.edit_signup_id.text()
            # self.patient["gender"] = self.combobox_signup_gender.currentText()
            # self.patient["max"] = 0
            # self.patient["min"] = 0
            # self.db.setPatient(self.patient)

        except:
            self.popUp()

    def loadDatabase(self):
        try:
            patients = self.db.getPatient(all = True)
            for patient in patients.val():
                pass
        except:
            print("error")

    # move whole application when dragging the header
    def mousePressEvent(self, event):
        if self.frame_main_head.geometry().contains(event.pos()):
            self.drag_position = event.globalPos() - self.frameGeometry().topLeft()
            event.accept()
        else:
            super(Ui_MainWindow, self).mousePressEvent(event)

    # move whole application when dragging the header
    def mouseMoveEvent(self, event):
        if event.buttons() and event.buttons() & QtCore.Qt.LeftButton and self.frame_main_head.geometry().contains(event.pos()):
            self.move(event.globalPos() - self.drag_position)
            event.accept()
        else:
            super(Ui_MainWindow, self).mouseMoveEvent(event)

    # maximize window using double click on header
    def mouseDoubleClickEvent(self, event):
        state = self.isMaximized()
        if event.button() == QtCore.Qt.LeftButton and self.frame_main_head.geometry().contains(event.pos()):
            self.sizeUi(not state)

    def changeEvent(self, event):
        if event.type() == QtCore.QEvent.WindowStateChange:
            if self.windowState() & QtCore.Qt.WindowMinimized:
                self.button_database_size.setChecked(False)
                self.button_main_size.setChecked(False)
                self.button_graph_size.setChecked(False)
                self.button_login_size.setChecked(False)
                self.button_signup_size.setChecked(False)
            elif self.windowState() & QtCore.Qt.WindowMaximized:
                self.button_database_size.setChecked(True)
                self.button_main_size.setChecked(True)
                self.button_graph_size.setChecked(True)
                self.button_login_size.setChecked(True)
                self.button_signup_size.setChecked(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mas Randi"))
        self.label_main_menu.setText(_translate("MainWindow", "MENU"))
        self.label_main_dash.setText(_translate("MainWindow", "DASHBOARD"))
        self.label_main_mainlabel.setText(_translate("MainWindow", "Main Menu"))
        self.button_main_login.setStyleSheet(_translate("MainWindow", "0"))
        self.button_main_login.setText(_translate("MainWindow", "Login"))
        self.button_main_signup.setText(_translate("MainWindow", "Sign-up"))
        self.button_main_database.setText(_translate("MainWindow", "Database"))
        self.label_login_menu.setText(_translate("MainWindow", "MENU"))
        self.label_login_dash.setText(_translate("MainWindow", "DASHBOARD"))
        self.edit_login_id.setPlaceholderText(_translate("MainWindow", "ID Pasien"))
        self.label_login_title.setText(_translate("MainWindow", "LOG IN"))
        self.button_login_sign.setText(_translate("MainWindow", "Belum Mendaftar?"))
        self.button_login_log.setText(_translate("MainWindow", "Log In"))
        self.label_signup_menu.setText(_translate("MainWindow", "MENU"))
        self.label_signup_dash.setText(_translate("MainWindow", "DASHBOARD"))
        self.label_signup_label1.setText(_translate("MainWindow", "CREATE PATIENT"))
        self.edit_signup_id.setPlaceholderText(_translate("MainWindow", "Daftarkan ID"))
        self.edit_signup_name.setPlaceholderText(_translate("MainWindow", "Nama Pasien"))
        self.edit_signup_age.setPlaceholderText(_translate("MainWindow", "Umur Pasien"))
        self.label_signup_gender.setText(_translate("MainWindow", "Gender Pasien:"))
        self.combobox_signup_gender.setCurrentText(_translate("MainWindow", "Male"))
        self.combobox_signup_gender.setItemText(0, _translate("MainWindow", "Male"))
        self.combobox_signup_gender.setItemText(1, _translate("MainWindow", "Female"))
        self.button_signup_sign.setText(_translate("MainWindow", "CREATE"))
        self.label_database_menu.setText(_translate("MainWindow", "MENU"))
        self.label_database_dash.setText(_translate("MainWindow", "DASHBOARD"))
        self.table_database_data.setSortingEnabled(True)
        item = self.table_database_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.table_database_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nama"))
        item = self.table_database_data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Usia"))
        item = self.table_database_data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        self.label_graph_tlabel.setText(_translate("MainWindow", "PLOT GRAPH"))
        self.button_graph_gbutton.setText(_translate("MainWindow", "Main Graph"))
        self.button_graph_avbbutton.setText(_translate("MainWindow", "Average Graph"))
        self.button_graph_setting.setText(_translate("MainWindow", "Settings"))
        self.label_graph_crlabel1.setText(_translate("MainWindow", "Surface Gating App"))
        self.label_graph_crlabel2.setText(_translate("MainWindow", "For Education Purposes Only"))
        self.label_graph_crlabel3.setText(_translate("MainWindow", "All Rights Reserved"))
        self.label_graph_menu.setText(_translate("MainWindow", "MENU"))
        self.label_graph_dash.setText(_translate("MainWindow", "DASHBOARD"))
        self.label_32.setText(_translate("MainWindow", "Main Graph"))
        self.label_33.setText(_translate("MainWindow", "Sensor 1 Graph"))
        self.label_34.setText(_translate("MainWindow", "Sensor 2 Graph"))
        self.button_graph_start.setText(_translate("MainWindow", "Start"))
        self.button_graph_stop.setText(_translate("MainWindow", "Stop"))
        self.button_graph_save.setText(_translate("MainWindow", "Save"))
        self.label_graph_id.setText(_translate("MainWindow", "ID"))
        self.label_graph_name.setText(_translate("MainWindow", "Nama"))
        self.label_graph_gender.setText(_translate("MainWindow", "Gender"))
        self.label_graph_age.setText(_translate("MainWindow", "Umur"))
        self.combo_graph_sensors.setCurrentText(_translate("MainWindow", "Sensors Graph"))
        self.combo_graph_sensors.setItemText(0, _translate("MainWindow", "Sensors Graph"))
        self.combo_graph_sensors.setItemText(1, _translate("MainWindow", "Sensor 1"))
        self.combo_graph_sensors.setItemText(2, _translate("MainWindow", "Sensor 2"))
        self.combo_graph_sensors.setItemText(3, _translate("MainWindow", "Sensor 3"))
        self.combo_graph_sensors.setItemText(4, _translate("MainWindow", "Sensor 4"))
        self.combo_graph_sensors.setItemText(5, _translate("MainWindow", "Sensor 5"))
        self.combo_graph_sensors.setItemText(6, _translate("MainWindow", "Sensor 6"))
        self.combo_graph_sensors.setItemText(7, _translate("MainWindow", "Sensor 7"))
        self.combo_graph_sensors.setItemText(8, _translate("MainWindow", "Sensor 8"))
        self.combo_graph_sensors.setItemText(9, _translate("MainWindow", "Sensor 9"))
        self.label_graph_max.setText(_translate("MainWindow", "Max : 100 mm"))
        self.label_graph_min.setText(_translate("MainWindow", "Min : 2 mm"))
        self.label_graph_avg.setText(_translate("MainWindow", "Average : 51 mm"))
        self.label_graph_rate.setText(_translate("MainWindow", "Rate : 3 mm/s"))

class customMessageBoz(QtWidgets.QMessageBox):
    pass



# import resources_rc
